import { EventContext, TraceEvent } from "protocol";
import { describe, expect, it } from "vitest";
import { parse as parseV140 } from "../ParseTraceSlaveWorker";
import { normalizeConstant } from "../normalize";
import { parseProperty } from "../parseProperty";
import { upgradeTrace } from "../upgradeTrace";

/**
 * LEGACY COMPAT — holds `upgradeTrace` plus the `parseToken` scope shim to the
 * behaviour of the parser they replaced, across every legacy trace checked into
 * `resources/traces`.
 *
 * The committed snapshots were generated by running the old
 * `components/renderer/parser` over these traces, and asserting
 * component-for-component that the upgraded output matched, before that parser
 * was deleted. They are the surviving record of what it did: a diff here means
 * the upgrade path has drifted from the format it is emulating.
 *
 * Two dialects live in the corpus:
 *
 * - `$.event` (1.0.5+) — the legacy parser rendered these, so their snapshots
 *   are its exact output.
 * - `ctx` (1.0.4 and its `converted/` output) — the legacy parser *threw*
 *   `ReferenceError: ctx is not defined` on these, having only ever bound `$`.
 *   They render for the first time via the `ctx` alias in `parseToken`, so
 *   their snapshots are a regression pin, not evidence of equivalence.
 */

/** Every legacy trace in the repo, keyed by its path under `resources/traces`. */
const modules = import.meta.glob<{ default: LegacyTraceFile }>(
  "../../../../../../resources/traces/{v1.0.4,v1.0.4/converted,v1.0.5,v1.0.5a}/*.json",
  { eager: true },
);

type LegacyTraceFile = {
  events?: { id: string | number }[];
  render?: { views?: { main?: { components?: unknown[] } } };
};

const context: EventContext = {
  theme: { foreground: "#ffffff", background: "#000000", accent: "#ff0000" },
  color: { red: "#f00", green: "#0f0", blue: "#00f" },
  themeAccent: "#ff0000",
  themeTextPrimary: "#ffffff",
  themeBackground: "#000000",
};

/** Events to compile per trace. Enough to exercise parent/step lookback. */
const STEPS = 8;

type Entry = { component: Record<string, unknown> };

/**
 * Compiled components carry the persistence flag as an ordinary prop, under a
 * different name in each format. Drop it — the split it drives is compared
 * separately, through which bucket the component lands in.
 */
function strip({ component }: Entry) {
  const { display: _display, clear: _clear, ...rest } = component;
  return rest;
}

const isVisible = ({ component: c }: Entry) =>
  c && Object.hasOwn(c, "alpha") ? (c.alpha as number) > 0 : true;

function upgradedOutput(trace: unknown, to: number) {
  const { trace: upgraded } = upgradeTrace(trace as never);
  const frames = parseV140({ trace: upgraded, context, to } as never);
  return {
    persistent: frames.map((f) => (f.components.persistent ?? []).filter(isVisible).map(strip)),
    transient: frames.map((f) => (f.components.transient ?? []).filter(isVisible).map(strip)),
  };
}

const count = (o: ReturnType<typeof upgradedOutput>) =>
  o.persistent.flat().length + o.transient.flat().length;

const corpus = Object.entries(modules)
  .map(([path, module]) => ({
    name: path.slice(path.indexOf("traces/") + "traces/".length),
    trace: module.default,
  }))
  .sort((a, b) => a.name.localeCompare(b.name))
  // A trace with no components compiles to nothing and would pass vacuously.
  .filter(({ trace }) => trace?.events?.length && trace?.render?.views?.main?.components?.length)
  .map((t) => ({ ...t, ctxDialect: JSON.stringify(t.trace.render).includes("ctx.") }));

const equivalent = corpus.filter((t) => !t.ctxDialect);
const ctxDialect = corpus.filter((t) => t.ctxDialect);

describe("upgraded traces compile identically to the legacy parser", () => {
  it("found traces of both dialects", () => {
    expect(equivalent.length).toBeGreaterThan(0);
    expect(ctxDialect.length).toBeGreaterThan(0);
  });

  describe.each(equivalent)("$name", ({ trace }) => {
    const to = Math.min(STEPS, trace.events?.length ?? 0);
    it("matches the legacy parser component-for-component", () => {
      const actual = upgradedOutput(trace, to);
      expect(count(actual)).toBeGreaterThan(0);
      // Snapshot taken from the legacy parser's own output. See the file note.
      expect(actual).toMatchSnapshot();
    });
  });

  describe.each(ctxDialect)("$name (ctx dialect)", ({ trace }) => {
    const to = Math.min(STEPS, trace.events?.length ?? 0);
    it("renders once upgraded", () => {
      const actual = upgradedOutput(trace, to);
      expect(count(actual)).toBeGreaterThan(0);
      // A regression pin on the upgrade — the legacy parser threw on these, so
      // there is no equivalent output to compare against.
      expect(actual).toMatchSnapshot();
    });
  });
});

describe("upgradeTrace", () => {
  it("is idempotent", () => {
    const once = upgradeTrace({ version: "1.0.5", render: { views: { main: [] } } } as never);
    const twice = upgradeTrace(once.trace);
    expect(twice.trace).toEqual(once.trace);
    expect(twice.from).toBeUndefined();
  });

  it("leaves a v1.4.0 trace untouched", () => {
    const trace = { version: "1.4.0" as const, views: { main: [] }, events: [] };
    const { trace: out, from } = upgradeTrace(trace);
    expect(out).toBe(trace);
    expect(from).toBeUndefined();
  });

  it("preserves the events array by reference", () => {
    const events = [{ id: 1 }];
    const { trace } = upgradeTrace({ version: "1.0.5", render: {}, events } as never);
    expect(trace.events).toBe(events);
  });

  it("flattens templates and views into one namespace", () => {
    const { trace } = upgradeTrace({
      version: "1.0.5",
      render: { components: { tile: [{ $: "rect" }] }, views: { main: [{ $: "tile" }] } },
    } as never);
    expect(Object.keys(trace.views!).sort()).toEqual(["main", "tile"]);
  });

  it("warns when a view and a component collide", () => {
    const { warnings } = upgradeTrace({
      version: "1.0.5",
      render: { components: { main: [{ $: "rect" }] }, views: { main: { components: [] } } },
    } as never);
    expect(warnings).toHaveLength(1);
    expect(warnings[0]).toMatch(/both named 'main'/);
  });

  it("converts display to clear", () => {
    const { trace } = upgradeTrace({
      version: "1.0.5",
      render: {
        views: {
          main: {
            components: [
              { $: "a", display: "transient" },
              { $: "b", display: "persistent" },
              { $: "c" },
            ],
          },
        },
      },
    } as never);
    expect(trace.views!.main).toEqual([{ $: "a", clear: true }, { $: "b" }, { $: "c" }]);
  });

  it("moves a legacy path to a pivot, baking in the scale factor", () => {
    const { trace } = upgradeTrace({
      version: "1.0.5",
      path: { pivot: { x: "{{$.event.x}}" }, scale: 0.3 },
    } as never);
    expect(trace.pivot).toEqual({ x: "${{$.event.x}}", scale: 1 });
  });

  it("defaults a falsy legacy scale to 1, as the old pivot read did", () => {
    const { trace } = upgradeTrace({ version: "1.0.5", path: { pivot: {} } } as never);
    expect(trace.pivot!.scale).toBe(1);
  });
});

/**
 * `use2DPath` evaluates the pivot against a bare event rather than a full frame
 * scope. Both pivot dialects have to resolve through it — see the LEGACY COMPAT
 * note there.
 */
describe("pivot expressions evaluate against a bare event", () => {
  const evaluate = (expression: string, event: Partial<TraceEvent>) =>
    parseProperty(expression)(normalizeConstant({ ...event, __internal__: { event } }));

  it("resolves a legacy pivot reading $.event", () => {
    expect(evaluate("${{'x' in $.event ? $.event.x : 0}}", { x: 5 })).toBe(5);
    expect(evaluate("${{'x' in $.event ? $.event.x : 0}}", {})).toBe(0);
  });

  it("resolves a v1.4.0 pivot reading $ directly", () => {
    expect(evaluate("${{ $.x + 0.5 }}", { x: 5 })).toBe(5.5);
  });
});

describe("upgradeTrace interpolation", () => {
  it("rewrites interpolation delimiters without touching events", () => {
    const events = [{ id: 1, label: "{{ literal }}" }];
    const { trace } = upgradeTrace({
      version: "1.0.5",
      render: { views: { main: { components: [{ $: "a", x: "{{ $.event.x }}" }] } } },
      events,
    } as never);
    expect(trace.views!.main[0].x).toBe("${{ $.event.x }}");
    expect(trace.events![0].label).toBe("{{ literal }}");
  });
});
